### ISSUE TITLE
downloading issue

### ISSUE THREAD

**Issue by pengxie-bioinfo** [tanaylab/embflow#1]
Hello, 

I'm trying to download/initialize the scRNA database (~ 4.7 GB) by 'source("scripts/download_data.r")' when the following issue raised:

trying URL 'http://www.wisdom.weizmann.ac.il/~atanay/embflow/scrna_db_embflow.tar.gz'
Content type 'application/x-gzip' length 4888328904 bytes (4661.9 MB)

downloaded 10.9 MB

Error in download.file("http://www.wisdom.weizmann.ac.il/~atanay/embflow/scrna_db_embflow.tar.gz",  : 
  download from 'http://www.wisdom.weizmann.ac.il/~atanay/embflow/scrna_db_embflow.tar.gz' failed
In addition: Warning messages:
1: In download.file("http://www.wisdom.weizmann.ac.il/~atanay/embflow/scrna_db_embflow.tar.gz",  :
  downloaded length 11449558 != reported length 4888328904
2: In download.file("http://www.wisdom.weizmann.ac.il/~atanay/embflow/scrna_db_embflow.tar.gz",  :
  URL 'http://www.wisdom.weizmann.ac.il/~atanay/embflow/scrna_db_embflow.tar.gz': status was 'Failure when receiving data from the peer'

Any ideas or is it possible to get around?

Best,
Peng

**Comment by aviezerl** [comment]
Hi Peng, 

This error is usually caused by network speed, see for example: 

https://stackoverflow.com/questions/27583767/warning-downloaded-length-reported-length-in-installing-packages-from-cran

I suggest downloading the file outside of R and then running the rest of the script:

```bash
wget http://www.wisdom.weizmann.ac.il/~atanay/embflow/scrna_db_embflow.tar.gz
tar -xvf scrna_db_embflow.tar.gz scrna_db
mkdir -p figs/paper_figs
```

Aviezer

**Comment by ShobiStassen** [comment]
@aviezerl 
Hi, I am trying to download the file using wget http (and also tried https) but  it says the connection keeps getting reset by peer so the download restarts every 30 seconds or so. Any thoughts on how to solve this? or how else I can download the data? After about 200+ attempts (~100MB downloaded) it gives up on trying to incrementally download the file
Thanks so much
Shobi

--2022-11-09 14:35:13--  (try:12)  https://www.wisdom.weizmann.ac.il/~atanay/embflow/scrna_db_embflow.tar.gz
Connecting to www.wisdom.weizmann.ac.il (www.wisdom.weizmann.ac.il)|132.76.150.110|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 4888328904 (4.6G), 4832525000 (4.5G) remaining [application/x-gzip]
Saving to: ‘scrna_db_embflow.tar.gz’

scrna_db_embflow.ta   1%[                    ]  62.23M   168KB/s    in 1m 43s  

2022-11-09 14:36:58 (89.8 KB/s) - Read error at byte 65257472/4888328904 (Connection reset by peer). Retrying.

**Comment by aviezerl** [comment]
I uploaded the files to an alternative location at AWS and updated the download script. 

You can download them directly from: 

- https://embflow.s3.eu-west-1.amazonaws.com/data_embflow.tar.gz
- https://embflow.s3.eu-west-1.amazonaws.com/scrna_db_embflow.tar.gz

**Comment by ShobiStassen** [comment]
Thank you! worked like a charm!
